version: '3.3'
services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - '8888:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: hbuezoss@gmail.com
      PGADMIN_DEFAULT_PASSWORD: alcancia..89
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  postgres:
    image: postgres:14
    restart: always
    env_file:
      - .env
    environment:
      tz: 'gmt-6'
      pgtz: 'gmt-6'
    ports:
      - '5435:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/mydata
volumes:
  postgres_data: {}
  pgadmin-data:
